### ISSUE TITLE
서비스 테이블 네이밍 변경

### ISSUE THREAD

**Issue by Seogeurim** [telbby/telbby-backend#18]
## 기능 설명 

백엔드 로직에서 `service`라는 네이밍을 사용할 시 서비스 계층과 혼돈이 있어서 테이블 네이밍을 변경합니다.
좋은 네이밍에 대해 댓글 남겨주세요~

## 진행 사항 

- [x] `service`에서 `project`로 변경
- [x] ERD 문서 변경
- [x] API 문서 변경

**Comment by jiyong1** [comment]
Project..?

**Comment by Seogeurim** [comment]
ERD 문서 변경 https://github.com/telbby/telbby-wiki/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-ERD

**Comment by Seogeurim** [comment]
API 문서 변경 https://github.com/telbby/telbby-wiki/wiki/API-%EB%AA%85%EC%84%B8#-projects-api
\+ postman도 변경함
