### ISSUE TITLE
회원가입 사용자 정보 validation 추가

### ISSUE THREAD

**Issue by Seogeurim** [telbby/telbby-backend#6]
## 기능 설명 

회원가입 사용자 정보 관련 validation 로직 중 아직 정책을 결정하지 못해 추가하지 못한 부분을 완료합니다.

> 해당 PR : https://github.com/telbby/telbby-backend/pull/5#discussion_r742486907

## 진행 사항 

- [x] 정규식 패턴 추가

**Comment by Seogeurim** [comment]
4주차 마일스톤에서 해당 이슈를 제외하고는 구현할 부분이 남아있지 않은 것이 맞을까요?..?.?. ㅎㅎㅎ
이 이슈 구현 후 dev merge되면 main에 한 번 merge 가시죠 !!

**Comment by hseoy** [comment]
로그인된 사용자 정보를 가져오는 API까지 작업하는 걸 생각했는 데 생각해보니까 현재 사용자 정보 필드에 userId 밖에 없어서 그 효용성이 떨어지네요,,, 나중에 추가해도 괜찮다고 생각했습니다.

말씀하신대로 이 이슈까지 구현하고 merge 한번 하는 게 좋을 것 같아요~~!!!
